source 'https://rubygems.org'

gem 'sugarcube', '~> 0.20', require: false
gem 'motion-redgreen', '~> 0.1'

# Other popular gems; uncomment as needed
# gem 'bubble-wrap', '~> 1.3'
# gem 'teacup', '~> 2.0'
# gem 'sweettea', '~> 0.5'
# gem 'motion-stump', '~> 0.2'
# gem 'formotion', '~> 1.3'