source 'https://rubygems.org'

gem 'motion-i18n', '~> 0.0.2'
gem 'i18n_tools', '~> 0.1', :require => 'i18n_tools/tasks'
gem 'sugarcube', '~> 1.0', :require => 'sugarcube-classic'
gem 'motion-redgreen', '~> 0.1'
gem 'motion-testflight', '~> 1.5'

# Other popular gems; uncomment as needed
# gem 'bubble-wrap', '~> 1.3'
# gem 'teacup', '~> 2.0'
# gem 'sweettea', '~> 0.5'
# gem 'motion-stump', '~> 0.3'
# gem 'formotion', '~> 1.3'